### PR TITLE
debian: use USRLIBDIR instead of patch

### PR DESCRIPTION
**Pull request by fepitre**
https://github.com/QubesOS/qubes-issues/issues/7134

### CODE REVIEW

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Pull request merged**
