### PR TITLE
Move security warning to qubes-doc

### PR DESCRIPTION
**Pull request by andrewdavidwong**
See: https://github.com/QubesOS/qubes-doc/pull/310#discussion_r106574106

### CODE REVIEW

**Comment by jpouellet** [comment]
I understand the desire to avoid duplicate things getting out of sync, but this also makes it less likely to be read. Are you sure this is where it should go?

**Comment by andrewdavidwong** [comment]
If you have a better idea, I'm all ears. :)

**Comment by andrewdavidwong** [comment]
Some additional thoughts:

It's true that not having the full text of the notice here makes it less likely to be read by people viewing this repo, but the same would be true if the full notice were not in the docs (but instead only linked to here from there). The question is which place gets more traffic from people who need to see the notice. It seems clear to me that the answer is: the docs.

**Comment by jpouellet** [comment]
Relevant:
- https://github.com/QubesOS/qubes-issues/issues/2329
- https://github.com/QubesOS/qubes-issues/issues/2736

If we take the route of installing sys-usb by default and auto-detecting whether or not to use the input proxy, this would be a very good warning to have in the installer or on first boot or so.

@andrewdavidwong Your argument re: warning here vs. docs sounds good to me. No objection from me to merging this.

**Pull request merged**
